---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/tasks":
    get:
      summary: Lists all tasks
      tags:
      - Tasks
      responses:
        '200':
          description: Tasks list
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
    post:
      summary: Creates a task
      tags:
      - Tasks
      parameters: []
      responses:
        '201':
          description: Task created
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  title:
                    type: string
                  created_at:
                    type: string
                    format: date-time
                  updated_at:
                    type: string
                    format: date-time
                required:
                - id
                - title
                - created_at
                - updated_at
        '422':
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: string
                required:
                - errors
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                task:
                  type: object
                  properties:
                    title:
                      type: string
                      example: Test
                  required:
                  - title
              required:
              - task
  "/api/tasks/{id}/completed":
    patch:
      summary: Marks a task as completed
      tags:
      - Tasks
      parameters:
      - name: id
        in: path
        description: Task ID
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: Task marked as completed
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  title:
                    type: string
                  description:
                    type: string
                    nullable: true
                required:
                - id
                - title
        '404':
          description: Task not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                required:
                - error
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
