---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/tasks":
    get:
      summary: Lists all tasks
      tags:
      - Tasks
      responses:
        '200':
          description: Tasks list
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
